#!/bin/bash

#Libraries need a ldconfig

ldconfig

echo $URL > /usr/src/app/url.txt
echo $CHROMIUM_ARGS > /usr/src/app/chromium_args.txt

# SSH server
sudo update-rc.d ssh defaults
mkdir ~/.ssh 2>&1
echo $SSH_KEY1 > ~/.ssh/authorized_keys
echo $SSH_KEY2 >> ~/.ssh/authorized_keys
echo $SSH_KEY3 >> ~/.ssh/authorized_keys

useradd -m pi

gpasswd -a pi video

cp /app/xinitrc /home/pi/.xinitrc;
chown pi: /home/pi/.xinitrc

su - pi -c startx &
